CREATE TABLE iPessoa(
	Codigo_Origem										VARCHAR(20),       		
	Codigo_Pessoa_Origem								VARCHAR(20),       		
	Codigo_Pessoa_Destino								VARCHAR(20), 				  
	Codigo_Cliente_Origem								VARCHAR(20),       		
	Codigo_Cliente_Destino								VARCHAR(20), 				  
	Codigo_Fornecedor_Origem							VARCHAR(20),       		
	Codigo_Fornecedor_Destino							VARCHAR(20), 				  
	Codigo_Transportadora_Origem						VARCHAR(20),       		
	Codigo_Transportadora_Destino						VARCHAR(20), 				  
	Codigo_Vendedor_Origem								VARCHAR(20),       		
	Codigo_Vendedor_Destino								VARCHAR(20), 	
	Codigo_Empresa_Origem								VARCHAR(20),       		
	Codigo_Empresa_Destino								VARCHAR(20), 				  
	Cliente												VARCHAR(10),	
	Fornecedor											VARCHAR(10),		
	Transportadora										VARCHAR(10),			
	Vendedor											VARCHAR(10),					
	Empresa												VARCHAR(10),						
	Fisica												VARCHAR(10),
	Juridica											VARCHAR(10),
	Status												VARCHAR(7),	
	Razao_Social										VARCHAR(100),  
	Nome_Fantasia                      					VARCHAR(100),	
	Endereco_Codigo_Tipo_Logradouro						VARCHAR(10),
	Endereco_Tipo_Logradouro           					VARCHAR(30),	
	Endereco_Logradouro                					VARCHAR(80),
	Endereco_Numero                    					VARCHAR(10),
	Endereco_Complemento               					VARCHAR(20),
	Endereco_Bairro                    					VARCHAR(50),
	Endereco_Municipio                 					VARCHAR(50),
	Endereco_UF                        					VARCHAR(2),
	Endereco_CEP                       					VARCHAR(10),
	Endereco_Cod_IBGE                  					VARCHAR(10),
	Endereco_Pais	                  					VARCHAR(20),		
	Tipo_Endereco										VARCHAR(20),
	Endereco_Principal									VARCHAR(3),	
	Endereco_Entrega									VARCHAR(3),		
	Endereco_Cobranca									VARCHAR(3),
	Endereco_Correspondencia							VARCHAR(3),	
	Telefone_DDD                       					VARCHAR(5),
	Telefone_Numero                    					VARCHAR(20),
	Telefone_Cormecial_DDD             					VARCHAR(5),
	Telefone_Cormecial_Numero          					VARCHAR(20),
	FAX_DDD                       						VARCHAR(5),
	FAX_Numero                    						VARCHAR(20),
	Celular_DDD                        					VARCHAR(5),
	Celular_Numero                     					VARCHAR(20),
	Email	                           					VARCHAR(50),
	Email2	                           					VARCHAR(50),
	Site                               					VARCHAR(50),	
	Sexo												VARCHAR(1),
	Estado_Civil										VARCHAR(10),
    CNPJ_CPF											VARCHAR(20),   
    Numero_RG											VARCHAR(20),
	RG_Orgao_Emissor                   					VARCHAR(10),
	Tipo_Regime											VARCHAR(20),
	Codigo_Regime_Tributario							VARCHAR(20),
	Data_Inicio_Atividades             					DATE,
	Data_Encerramento_Atividades       					DATE,
	Data_Nascimento										DATE,
	Capital_Social										NUMERIC(20, 2),
	Inscricao_Estadual                 					VARCHAR(20),
	Inscricao_Municipal                					VARCHAR(20),
	Codigo_Banco										VARCHAR(10),
	Tipo_Conta_Banco									VARCHAR(50),
	Numero_Agencia_Banco								VARCHAR(10),		
	Digito_Agencia_Banco								VARCHAR(2),	
	Numero_Conta_Banco									VARCHAR(10),
	Digito_Conta_Banco									VARCHAR(2),	
	Data_Admissao                       				DATE, 
	Data_Desligamento									DATE,							
	CTPS_Numero                        					VARCHAR(20),       
	PIS_PASEP_Numero                   					VARCHAR(20),       
	Titulo_Eleitor_Numero              					VARCHAR(20),
	Reservista_Numero                  					VARCHAR(20),
	Pai_Nome                           					VARCHAR(80),
	Mae_Nome                           					VARCHAR(80),
	Nome_Conjuge										VARCHAR(50),
	Data_Nascimento_Conjuge								DATE,
	Nacionalidade										VARCHAR(50),
	Naturalidade										VARCHAR(50),	
	Codigo_Cargo										VARCHAR(10),			
	Desc_Cargo											VARCHAR(50),
	Salario												NUMERIC(20, 2),				
	Possui_limite                     					VARCHAR(3),
	Limite_Credito										NUMERIC(20, 2),
	Limite												NUMERIC(20, 2),
	Saldo												NUMERIC(20, 2),
	CEI                                					VARCHAR(20),	
	Optante_Simples										VARCHAR(3),	
	Contribuinte_ICMS									VARCHAR(30),
	Data_ICMS_Simples			       					DATE,			
	Data_ISS_Simples									DATE,			
	Numero_Suframa                     					VARCHAR(20),
	Possui_eSocial                     					VARCHAR(3),
	Numero_CNAE                        					VARCHAR(7),
	Natureza_Juridica                  					VARCHAR(10),   
	Categoria                          					VARCHAR(1),
	Tipo_Pagamento                   					VARCHAR(10),   
	Aliquota_INSS_Folha                					NUMERIC(4, 2),
	Aliquota_INSS_ProLabore_RPA        					NUMERIC(4, 2),
	Aliquota_RAT                       					NUMERIC(4, 2),
	Numero_FAP                         					VARCHAR(10),
	Aliquota_Terceiros                 					NUMERIC(4, 2),
	Numero_Proprietarios               					INT,
	Classificacao_Tributaria           					VARCHAR(1),          
	Indicativo_Cooperativa	           					VARCHAR(1),			
	Indicativo_Construtora             					VARCHAR(1),		
	Indicativo_Entidade_Educativa      					VARCHAR(1),		
	Indicativo_Trabalho_Temporario     					VARCHAR(1),		
	Indicativo_Contratacao_Aprendiz    					VARCHAR(1),		
	Indicativo_ECD										VARCHAR(1),		
	Indicativo_Empresa_Trabalho_Temporario				VARCHAR(1),		
	Indicativo_Entidade_Educativa_Sem_Fins_Lucrativo 	VARCHAR(1),		
	Registro_Eletronico_Empregados     					VARCHAR(1),    
	Controle_Ponto                     					INT,            
	Produtor_Rural        								VARCHAR(3),
	Inscricao_Produtor_Rural        					VARCHAR(20),
	Inscricao_nao_contribuinte							VARCHAR(20),
	Tipo_Colaborador									VARCHAR(20),
	Grau_Instrucao                      				VARCHAR(50),
	NFE_NFSE											VARCHAR(3),
	Regime												VARCHAR(20),	
	Atividades											VARCHAR(20),
	CRT													VARCHAR(20),
	Desconto_Porcentagem               					NUMERIC(4, 2),	
	Desconto_Fixo		               					NUMERIC(4, 2),		
	Codigo_Vendedor		            					VARCHAR(10),   	
	Codigo_Transportadora              					VARCHAR(10),   	
	Codigo_Departamento_Origem         					VARCHAR(10),
	Codigo_Setor_Origem                					VARCHAR(10),
	Codigo_Secao_Origem                					VARCHAR(10),
	Codigo_Sindicato_Patronal          					VARCHAR(10),	
	Codigo_Terceiros                   					VARCHAR(4),
	Codigo_Pagamento_GPS               					VARCHAR(4),	
	Codigo_FPAS                        					VARCHAR(4),
	Codigo_eSocial                     					VARCHAR(30),   
	Observacao											VARCHAR(254)
);		

CREATE TABLE iBancos (
    Codigo_Banco_Origem                					VARCHAR(10),       
	Codigo_Banco_Destino               					VARCHAR(10),       
	Codigo_Banco_FEBRABAN              					VARCHAR(10),       
    Nome                               					VARCHAR(50),       
	Agencia                            					VARCHAR(15),
	Agencia_DV                         					VARCHAR(2),
	Conta_Banco                         				VARCHAR(10),
	Endereco_Tipo_Logradouro           					VARCHAR(30),				
	Endereco_Logradouro                					VARCHAR(80),       
	Endereco_Numero                    					VARCHAR(10),       
	Endereco_Complemento               					VARCHAR(20),       
	Endereco_Bairro                    					VARCHAR(50),       
	Endereco_Municipio                 					VARCHAR(50),       
	Endereco_UF                        					VARCHAR(2),        
	Endereco_CEP                       					VARCHAR(10),
	Telefone_DDD                       					VARCHAR(5),
	Telefone_Numero                    					VARCHAR(20),
	Fax_DDD                            					VARCHAR(5),
	Fax_Numero                         					VARCHAR(20)

);                                     		

CREATE TABLE iCargos (                 		 
	Codigo_Cargo_Origem                					VARCHAR(10),       
	Codigo_Cargo_Destino               					VARCHAR(10),       
	Descricao                          					VARCHAR(50),       
	CBO                                					VARCHAR(10),
	CBO_2002                           					VARCHAR(10),				
	Descricao_Atividades            					VARCHAR(250)
);                                     		

CREATE TABLE iProdutos (                 		 
	Codigo_Cliente_Origem								VARCHAR(20),       		
	Codigo_Cliente_Destino								VARCHAR(20), 				  
	Codigo_Produto_Origem								VARCHAR(20),
	Codigo_Produto_Destino								VARCHAR(20),
	Codigo_Produto_Interno								VARCHAR(20),	
	Descricao											VARCHAR(250),
	Status												VARCHAR(7),	
	Codigo_Grupo_Origem									VARCHAR(20),
	Codigo_Sub_Grupo_Origem								VARCHAR(20),	
	Codigo_Unidade_Origem								VARCHAR(20),
	Codigo_Unidade_Venda_Origem							VARCHAR(20),
	Codigo_Marca_Origem									VARCHAR(20),
	Codigo_Deposito_Origem								VARCHAR(20),
    Codigo_Balanca										VARCHAR(10),		
	Codigo_Barras_Produto								VARCHAR(50),
    Codigo_Tributacao									VARCHAR(10),			
	Codigo_Fornecedor									VARCHAR(10),			
	Tipo_Produto_Servico								VARCHAR(10),
	Tipo_Produto										VARCHAR(10),
	Tipo_Servico										VARCHAR(10),
	Data_Incial_Produto									DATE,
	Data_Final_Produto									DATE,
	Descricao_ECF										VARCHAR(100),
	CF_Produto											VARCHAR(20),
	CST_Produto											VARCHAR(20),
	CFOP_Produto										VARCHAR(20),
	CSOSN_Produto										VARCHAR(20),
	Id_CEST_Produto										VARCHAR(20),
	CEST_Produto										VARCHAR(20),
	IAT_Produto											VARCHAR(20),
	IPPT_Produto										VARCHAR(20),
	Codigo_ANP_Produto									VARCHAR(20),
	UF_ANP_Produto										VARCHAR(2),
	Codigo_NCM											VARCHAR(20),
	ICMS												NUMERIC(20, 2),
	Base_ICMS											NUMERIC(20, 2),
	Aliquota_ICMS										NUMERIC(20, 2),
	Aliquota_PIS_Produto								NUMERIC(20, 2),
	Aliquota_COF_Produto								NUMERIC(20, 2),
	Reducao_ICMS										NUMERIC(20, 2),
	Modalidade_ICMS										VARCHAR(20),
	Substituicao_Tributaria_ICMS						NUMERIC(20, 2),
	Percentual_FCP_ICMS									NUMERIC(20, 4),
	Percentual_FCP_ICMS_ST								NUMERIC(20, 4),
	Indice_Escala_ICMS_ST								VARCHAR(20),
	CNPJ_Fabricacao_ICMS_ST								VARCHAR(20),
	Codigo_Beneficio_ICMS_ST							VARCHAR(20),
	Numero_Registro_CODDIF								VARCHAR(30),
	IPI													NUMERIC(20, 2),
	Base_IPI											NUMERIC(20, 2),
	Aliquota_IPI										NUMERIC(20, 2),
	Reducao_IPI											NUMERIC(20, 2),
	Cofins												NUMERIC(20, 2),			
	Comissao_Venda_Produto								NUMERIC(20, 2),
	Margem_Lucro_Produto								NUMERIC(20, 2),
	Valor_Custo_Produto									NUMERIC(20, 2),
	Valor_Custo_Produto_Bruto							NUMERIC(20, 2),	
	Valor_Venda_Produto1								NUMERIC(20, 2),
	Valor_Venda_Produto2								NUMERIC(20, 2),
	Valor_Venda_Produto3								NUMERIC(20, 2),
	Valor_FRETE_Produto 								NUMERIC(20, 2),	
	Valor_Fixo_Produto	 								NUMERIC(20, 2),		
	Fator_Unidade_Produto								NUMERIC(20, 2),
	Kit_Produto											VARCHAR(3),
	Kit_Produto_Valor									NUMERIC(20, 2),
	Lote_Produto_Controlado								VARCHAR(3),
	Serial_Produto_Controlado							VARCHAR(3),
	Utiliza_Balanca										VARCHAR(3),
	Peso_Produto 										NUMERIC(20, 2),
	Tamanho_Produto										VARCHAR(50),
	Composicao_Produto									VARCHAR(50),
	Origem_Produto										VARCHAR(20),
	Chave_Produto										VARCHAR(20),
	Materia_Prima_Produto								VARCHAR(50),
	Material_Expediente_Produto							VARCHAR(50),
	Fonte_Produto										VARCHAR(50),
	Validade_Produto									DATE,
	Consumir_produto									INT,
	Revenda_Produto										VARCHAR(3),
	Controle_Estoque									VARCHAR(3),
	Controle_Lote										VARCHAR(3),
	Controla_Validade									VARCHAR(3),
	Saldo_Negativo										VARCHAR(3),
	Tributacao											VARCHAR(10),
	Unidade_Venda_Produto								VARCHAR(10),						
	Quantidade_Produto									VARCHAR(10),							
	Quantidade_Produto_MAX								INT,							
	Quantidade_Produto_MIN								INT,							
	Corredor											VARCHAR(20),
	Prateleira											VARCHAR(20),	
	Observacao											VARCHAR(2000)	
);

CREATE TABLE iUnidades (
	Codigo_Unidades_Origem								VARCHAR(20),
	Codigo_Unidades_Destino								VARCHAR(20),
	Descricao											VARCHAR(100),
	Sigla												VARCHAR(20),
);

CREATE TABLE iGrupos_Produtos (
	Codigo_Grupo_Origem									VARCHAR(20),
	Codigo_Grupo_Destino								VARCHAR(20),
	Descricao											VARCHAR(100),
	Saldo_Negativo										VARCHAR(1)
);

CREATE TABLE iSub_Grupos_Produtos (
	Codigo_Sub_Grupo_Origem								VARCHAR(20),
	Codigo_Sub_Grupo_Destino							VARCHAR(20),
	Codigo_Grupo_Origem									VARCHAR(20),
	Codigo_Grupo_Destino								VARCHAR(20),
	Descricao											VARCHAR(100),
	Saldo_Negativo										VARCHAR(1)	
);

CREATE TABLE iMarcas (
	Codigo_Marca_Origem									VARCHAR(20),
	Codigo_Marca_Destino								VARCHAR(20),
	Descricao											VARCHAR(100),
);

CREATE TABLE iDepositos (
	Codigo_Depositos_Origem								VARCHAR(20),
	Codigo_Depositos_Destino							VARCHAR(20),
	Descricao											VARCHAR(100),
	Status												VARCHAR(7),	
	Data_Inicio_Atividades								DATE,	
	Data_Fim_Atividades									DATE	
);

CREATE TABLE iPlano_Contas (
	Codigo_Reduzido										VARCHAR(20),
	Classificacao										VARCHAR(50),
	Conta_Sintetica										VARCHAR(20),
	Nome												VARCHAR(100),
	Tipo												VARCHAR(20),
	Patrimonio_Resultado								VARCHAR(50),
	Natureza											VARCHAR(20),
	Situacao											VARCHAR(20),
	id													VARCHAR(20),	
	Data_Inclusao										DATE
);

CREATE TABLE iForma_Pagto (
	Codigo_Origem										VARCHAR(20),
	Codigo_Destino										VARCHAR(20),	
	Descricao 											VARCHAR(100),
	Valor_Maximo										NUMERIC(20, 2),	
	Valor_Minimo										NUMERIC(20, 2),		
	Nfe_Pagto											VARCHAR(1)
);

CREATE TABLE iTipo_Pagto (
	Codigo_Origem										VARCHAR(20),
	Codigo_Destino										VARCHAR(20),	
	Descricao 											VARCHAR(100),
	Sigla												VARCHAR(3),	
	Nfe_Pagto											VARCHAR(2),
	Padrao												VARCHAR(1)
);

CREATE TABLE iContatos (
	Codigo_Contatos_Origem								VARCHAR(20),
	Codigo_Contatos_Destino								VARCHAR(20),
	Codigo_Pessoa										VARCHAR(20),	
	Descricao											VARCHAR(100),
    Nome                               					VARCHAR(50),       	
	Status												VARCHAR(7),	
	Telefone_DDD                       					VARCHAR(5),
	Telefone_Numero                    					VARCHAR(20),
	Telefone_Cormecial_DDD             					VARCHAR(5),
	Telefone_Cormecial_Numero          					VARCHAR(20),
	Celular_DDD                        					VARCHAR(5),
	Celular_Numero                     					VARCHAR(20),
	Email	                           					VARCHAR(50),
	Email2	                           					VARCHAR(50),
	Email_Nfe                          					VARCHAR(1),
	Site                               					VARCHAR(50),	
);

CREATE TABLE iConta_a_Pagar (
	Codigo_Conta_a_Pagar_Origem							VARCHAR(20),
	Codigo_Conta_a_Pagar_Destino						VARCHAR(20),	
	Codigo_Pessoa_Origem								VARCHAR(20),       		
	Codigo_Pessoa_Destino								VARCHAR(20), 				  
	Codigo_Cliente_Origem								VARCHAR(20),       		
	Codigo_Cliente_Destino								VARCHAR(20), 				  
	Codigo_Empresa_Origem								VARCHAR(20),
	Codigo_Empresa_Destino								VARCHAR(20),
	Codigo_Fornecedor_Origem							VARCHAR(20),       		
	Codigo_Fornecedor_Destino							VARCHAR(20), 				  
	Codigo_Pedido_Compra_Origem							VARCHAR(20),       		
	Codigo_Pedido_Compra_Destino						VARCHAR(20), 				  
	Codigo_Documento_Origem_Destino						VARCHAR(20), 				  
	Numero_Documento_Origem								VARCHAR(20),
	Numero_Documento_Destino							VARCHAR(20),	
	Origem_Documento									VARCHAR(20),
	Codigo_NFe											VARCHAR(20),	
	Situacao											VARCHAR(20),
	Descicao_Situacao									VARCHAR(20),	
	Data_Emissao_Lancamento            					DATE,
	Data_Vencto_Lancamento            					DATE,
	Data_Pagamento_Lancamento          					DATE,
	Quantidade_Parcelas									INT,								
	Valor_Docto_Total									NUMERIC(20, 2),	
	Valor_Docto_a_Pagar									NUMERIC(20, 2),		
	Valor_Docto_Pago									NUMERIC(20, 2),			
	Valor_Frete_a_Pagar									NUMERIC(20, 2),	
	Valor_Seguro_a_Pagar								NUMERIC(20, 2),		
	Valor_Outras_Despesas_a_Pagar						NUMERIC(20, 2),		
	Valor_Juros_a_Pagar									NUMERIC(20, 2),			
	Valor_Multa_a_Pagar									NUMERIC(20, 2),				
	Observacao											VARCHAR(2000)	
);

CREATE TABLE iConta_a_Pagar_Parcela (
	Codigo_Parcela_a_Pagar_Origem						VARCHAR(20),
	Codigo_Parcela_a_Pagar_Destino						VARCHAR(20),	
	Codigo_Conta_a_Pagar_Origem							VARCHAR(20),
	Codigo_Conta_a_Pagar_Destino						VARCHAR(20),	
	Codigo_Conta_Caixa_Origem							VARCHAR(20),	
	Codigo_Conta_Caixa_Destino							VARCHAR(20),		
	Numero_Documento_Origem								VARCHAR(20),
	Numero_Documento_Destino							VARCHAR(20),	
	Situacao_Origem										VARCHAR(20),	
	Situacao_Destino									VARCHAR(20),		
	Descicao_Situacao									VARCHAR(20),		
	Tipo_Pagamento										VARCHAR(20),
	Forma_Pagamento										VARCHAR(20),	
	Data_Emissao_Lancamento            					DATE,
	Data_Vencto_Lancamento            					DATE,
	Data_Pagamento_Lancamento          					DATE,
	Quantidade_Parcelas									INT,								
	Valor_Docto_Total									NUMERIC(20, 2),	
	Valor_Docto_a_Pagar									NUMERIC(20, 2),		
	Valor_Docto_Pago									NUMERIC(20, 2),				
	Valor_Juros_a_Pagar									NUMERIC(20, 2),			
	Valor_Multa_a_Pagar									NUMERIC(20, 2),				
	Valor_Desconto										NUMERIC(20, 2),					
	Nr_Juros											NUMERIC(20, 2),							
	Nr_Multa											NUMERIC(20, 2),							
	Nr_Mora												NUMERIC(20, 2),							
	Nr_Outros											NUMERIC(20, 2),								
	Nr_Desconto											NUMERIC(20, 2),									
	Nr_Credito											NUMERIC(20, 2),										
	Observacao											VARCHAR(2000)	
);


CREATE TABLE iConta_a_Receber (
	Codigo_Conta_a_Receber_Origem						VARCHAR(20),
	Codigo_Conta_a_Receber_Destino						VARCHAR(20),	
	Codigo_Pessoa_Origem								VARCHAR(20),       		
	Codigo_Pessoa_Destino								VARCHAR(20), 				  
	Codigo_Cliente_Origem								VARCHAR(20),       		
	Codigo_Cliente_Destino								VARCHAR(20), 				  
	Codigo_Empresa_Origem								VARCHAR(20),
	Codigo_Empresa_Destino								VARCHAR(20),
	Codigo_Fornecedor_Origem							VARCHAR(20),       		
	Codigo_Fornecedor_Destino							VARCHAR(20), 				  
	Codigo_Pedido_Compra_Origem							VARCHAR(20),       		
	Codigo_Pedido_Compra_Destino						VARCHAR(20), 				  
	Codigo_Documento_Origem_Destino						VARCHAR(20), 				  
	Numero_Documento_Origem								VARCHAR(20),
	Numero_Documento_Destino							VARCHAR(20),	
	Origem_Documento									VARCHAR(20),
	Codigo_NFe											VARCHAR(20),	
	Situacao											VARCHAR(20),
	Descicao_Situacao									VARCHAR(20),	
	Data_Emissao_Lancamento            					DATE,
	Data_Vencto_Lancamento            					DATE,
	Data_Pagamento_Lancamento          					DATE,
	Data_Recebimento_Lancamento        					DATE,	
	Quantidade_Parcelas									INT,								
	Valor_Docto_Total									NUMERIC(20, 2),	
	Valor_Docto_a_Receber								NUMERIC(20, 2),		
	Valor_Docto_Pago									NUMERIC(20, 2),			
	Valor_Frete_a_Receber								NUMERIC(20, 2),	
	Valor_Seguro_a_Receber								NUMERIC(20, 2),		
	Valor_Outras_Despesas_a_Receber						NUMERIC(20, 2),		
	Valor_Juros_a_Receber								NUMERIC(20, 2),			
	Valor_Multa_a_Receber								NUMERIC(20, 2),				
	Valor_Desconto										NUMERIC(20, 2),					
	Valor_Abatimento									NUMERIC(20, 2),						
	Nr_Juros											NUMERIC(20, 2),							
	Nr_Multa											NUMERIC(20, 2),							
	Nr_Mora												NUMERIC(20, 2),							
	Nr_Outros											NUMERIC(20, 2),								
	Nr_Desconto											NUMERIC(20, 2),									
	Nr_Credito											NUMERIC(20, 2),										
	Tipo_Pagamento										VARCHAR(20),
	Forma_Pagamento										VARCHAR(20),	
	Previsto_Realizado									VARCHAR(20),	
	Conta_Caixa 										VARCHAR(20),
	Numero_Banco										VARCHAR(20),
	Digito_Banco										VARCHAR(20),	
	Agencia_Banco										VARCHAR(20),
	Observacao											VARCHAR(2000)	
);

CREATE TABLE iConta_a_Receber_Parcela (
	Codigo_Parcela_a_Receber_Origem						VARCHAR(20),
	Codigo_Parcela_a_Receber_Destino					VARCHAR(20),	
	Codigo_Conta_a_Receber_Origem						VARCHAR(20),
	Codigo_Conta_a_Receber_Destino						VARCHAR(20),	
	Codigo_Conta_Caixa_Origem							VARCHAR(20),	
	Codigo_Conta_Caixa_Destino							VARCHAR(20),		
	Numero_Documento_Origem								VARCHAR(20),
	Numero_Documento_Destino							VARCHAR(20),	
	Situacao_Origem										VARCHAR(20),	
	Situacao_Destino									VARCHAR(20),		
	Descicao_Situacao									VARCHAR(20),		
	Tipo_Pagamento										VARCHAR(20),
	Forma_Pagamento										VARCHAR(20),	
	Data_Emissao_Lancamento            					DATE,
	Data_Vencto_Lancamento            					DATE,
	Data_Pagamento_Lancamento          					DATE,
	Data_Recebimento_Lancamento        					DATE,		
	Quantidade_Parcelas									INT,								
	Valor_Docto_Total									NUMERIC(20, 2),	
	Valor_Docto_a_Receber								NUMERIC(20, 2),		
	Valor_Docto_Pago									NUMERIC(20, 2),				
	Valor_Juros_a_Receber								NUMERIC(20, 2),			
	Valor_Multa_a_Receber								NUMERIC(20, 2),				
	Valor_Desconto										NUMERIC(20, 2),					
	Nr_Juros											NUMERIC(20, 2),							
	Nr_Multa											NUMERIC(20, 2),							
	Nr_Mora												NUMERIC(20, 2),							
	Nr_Outros											NUMERIC(20, 2),								
	Nr_Desconto											NUMERIC(20, 2),									
	Nr_Credito											NUMERIC(20, 2),											
	Observacao											VARCHAR(2000)	
);

CREATE TABLE iEstoque (
	Codigo_Origem										VARCHAR(20),       		
	Codigo_Estoque_Origem								VARCHAR(20),       		
	Codigo_Estoque_Destino								VARCHAR(20),
	Descricao											VARCHAR(250),
	Status												VARCHAR(7),	
	Codigo_Produto_Origem								VARCHAR(20),
	Codigo_Produto_Destino								VARCHAR(20),
	Codigo_Deposito_Origem								VARCHAR(20),
	Codigo_Deposito_Destino								VARCHAR(20),	
	Codigo_Local_Deposito_Origem						VARCHAR(20),
	Codigo_Local_Deposito_Destino						VARCHAR(20),	
	Codigo_Grupo_Origem									VARCHAR(20),
	Codigo_Grupo_Destino								VARCHAR(20),	
	Codigo_Sub_Grupo_Origem								VARCHAR(20),	
	Codigo_Sub_Grupo_Destino							VARCHAR(20),		
	Codigo_Unidade_Origem								VARCHAR(20),
	Codigo_Unidade_Destino								VARCHAR(20),	
    Codigo_Balanca										VARCHAR(10),		
	Codigo_Barras_Produto								VARCHAR(50),
	Quantidade_Produto_Invetario						INT,								
	Quantidade_Produto									INT,							
	Quantidade_Produto_MAX								INT,							
	Quantidade_Produto_MIN								INT,							
	Data_Lancamento		            					DATE,
	Corredor											VARCHAR(20),
	Prateleira											VARCHAR(20),		
	Valor_Custo_Produto									NUMERIC(20, 2),
	Valor_Custo_Produto_Bruto							NUMERIC(20, 2),
	Valor_Atacado_Produto								NUMERIC(20, 2),
	Valor_Venda_Produto1								NUMERIC(20, 2),
	Valor_Venda_Produto2								NUMERIC(20, 2),
	Valor_Venda_Produto3								NUMERIC(20, 2),
	Valor_FRETE_Produto 								NUMERIC(20, 2),	
	Valor_Fixo_Produto	 								NUMERIC(20, 2),		
	Valor_Seguro										NUMERIC(20, 2),		
	Valor_Outras_Despesas								NUMERIC(20, 2),		
	Valor_Juros											NUMERIC(20, 2),			
	Valor_Multa											NUMERIC(20, 2),				
	Valor_Desconto										NUMERIC(20, 2),					
	Valor_Abatimento									NUMERIC(20, 2),						
	CF_Produto											VARCHAR(20),
	CST_Produto											VARCHAR(20),
	CFOP_Produto										VARCHAR(20),
	CSOSN_Produto										VARCHAR(20),
	Id_CEST_Produto										VARCHAR(20),
	CEST_Produto										VARCHAR(20),
	IAT_Produto											VARCHAR(20),
	IPPT_Produto										VARCHAR(20),
	Codigo_ANP_Produto									VARCHAR(20),
	UF_ANP_Produto										VARCHAR(2),
	Codigo_NCM											VARCHAR(20),
	ICMS												NUMERIC(20, 2),
	Base_ICMS											NUMERIC(20, 2),
	Aliquota_ICMS										NUMERIC(20, 2),
	Aliquota_PIS_Produto								NUMERIC(20, 2),
	Aliquota_COF_Produto								NUMERIC(20, 2),
	Reducao_ICMS										NUMERIC(20, 2),
	Modalidade_ICMS										VARCHAR(20),
	Substituicao_Tributaria_ICMS						NUMERIC(20, 2),
	Percentual_FCP_ICMS									NUMERIC(20, 4),
	Percentual_FCP_ICMS_ST								NUMERIC(20, 4),
	Indice_Escala_ICMS_ST								VARCHAR(20),
	CNPJ_Fabricacao_ICMS_ST								VARCHAR(20),
	Codigo_Beneficio_ICMS_ST							VARCHAR(20),
	Numero_Registro_CODDIF								VARCHAR(30),
	IPI													NUMERIC(20, 2),
	Base_IPI											NUMERIC(20, 2),
	Aliquota_IPI										NUMERIC(20, 2),
	Reducao_IPI											NUMERIC(20, 2),
	Cofins												NUMERIC(20, 2),
	Cofins_Porc											NUMERIC(20, 2),	
	PIS													NUMERIC(20, 2),	
	PIS_PORC											NUMERIC(20, 2),		
	Observacao											VARCHAR(2000)		
)

CREATE TABLE iEstoque_Lancamento (
	Codigo_Origem										VARCHAR(20),       		
	Codigo_Estoque_Origem								VARCHAR(20),       		
	Codigo_Estoque_Destino								VARCHAR(20),
	Codigo_Estoque_Local_Origem							VARCHAR(20),       		
	Codigo_Estoque_Local_Destino						VARCHAR(20),
	Codigo_Produto_Origem								VARCHAR(20),       		
	Codigo_Produto_Destino								VARCHAR(20),
	Corredor											VARCHAR(20),
	Prateleira											VARCHAR(20),			
	Tipo_Lancamento										VARCHAR(20),	
	Origem_Lancamento									VARCHAR(20),
	Quantidade_Produto									INT,								
	Data_Hora_Lancamento							    DATETIME,		
	Codigo_Transformacao_Origem							VARCHAR(20),
	Codigo_Transformacao_Destino						VARCHAR(20),
	Valor_Unitario	 									NUMERIC(20, 2),	
	Observacao											VARCHAR(2000)			
)